name: Trigger auto deployment for app-testjob

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/app-testjob-AutoDeployTrigger-2f65f1b1-569e-489c-b91d-8f3d1ca0c2a1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.APPTESTJOB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APPTESTJOB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APPTESTJOB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: acrtestjob.azurecr.io
          registryUsername: ${{ secrets.APPTESTJOB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APPTESTJOB_REGISTRY_PASSWORD }}
          containerAppName: app-testjob
          resourceGroup: rg-testjob
          imageToBuild: acrtestjob.azurecr.io/app-testjob:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


